name: Flutter Compile

on:
  push:
    branches:
      - '**'

jobs:
  compile:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Run CLEAN CACHE
        run: flutter clean cache

      - name: Run CLEAN
        run: flutter clean

      - name: Run DEPENDENCIES
        run: dart pub get

      - name: Run TEST
        run: flutter test -r github

      - name: Run COMPILE
        run: dart run build_runner build